name: Run Benchmarks

on:
  push:
    branches: [ skyhookdm-workflow ]
  pull_request:
    branches: [ skyhookdm-workflow ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: uccross/skyhookdm-arrow:v0.2.0
    steps:
      - uses: actions/checkout@v2
 
      - name: Setup Python
        run: |
          sudo apt update
          python3 -V
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt install python3.9
          sudo apt install -y python3-pip
          
      - name: Install Python dependencies
        run: |
          python3 setup.py develop
          pip3 install -r requirements-test.txt
          pip3 install -r requirements-build.txt
          pip3 install https://github.com/ursacomputing/conbench/archive/main.zip
          pip3 install coveralls
          
      - name: Run Tests
        run: |
          pytest -vv benchmarks/tests/
