name: Run Benchmarks

on:
  push:
    branches: [ skyhookdm-workflow, debug ]
  pull_request:
    branches: [ skyhookdm-workflow, debug ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: uccross/skyhookdm-arrow-benchmark:v0.2.0
      options: --privileged
    steps:
      - uses: actions/checkout@v2               
          
      - name: Install Python dependencies
        run: |
          python3.9 setup.py develop
          pip3.9 install -r requirements-test.txt
          pip3.9 install -r requirements-build.txt
          pip3.9 install coveralls
          
      - name: Setup Conbench
        run: |
          yum install postgresql-devel -y
          git clone https://github.com/ursacomputing/conbench.git
          cd conbench
          pip3.9 install -r requirements-test.txt
          pip3.9 install -r requirements-build.txt
          pip3.9 install -r requirements-cli.txt
          python3.9 setup.py develop
          
      - name: Setup Pyarrow with Skyhook
        run: |
          pip3.9 install --upgrade /pyarrow-*.whl
          
      - name: Run Tests
        run: |
          cp /usr/local/bin/python3.9 /usr/local/bin/python
          sh integration_ceph.sh
          #pytest -vv benchmarks/tests/test_dataset_filter_benchhmark.py
          
      - name: Save results as JSON
        run: |
          cd benchmarks/
          git clone https://github.com/uccross/skyhookdm-benchmarks.git
          cd skyhookdm-benchmarks
          mkdir -p benchmarks-result/$(date '+%Y-%m-%d')
          mkdir benchmarks-result/$(date '+%Y-%m-%d')/${{ github.sha }} 
          cd ..  
          for i in 1 2 5 10 14; do    conbench dataset-selectivity-column-parquet --selectivity=$i ALL | awk 'NR>2' > skyhookdm-benchmarks/benchmarks-result/$(date '+%Y-%m-%d')/${{ github.sha }}/dataset-selectivity-${i}-column-parquet.json; done
          for i in 1 2 5 10 14; do    conbench dataset-selectivity-column-rados --selectivity=$i ALL | awk 'NR>2' > skyhookdm-benchmarks/benchmarks-result/$(date '+%Y-%m-%d')/${{ github.sha }}/dataset-selectivity-${i}-column-rados.json; done
          for i in 1 10 25 50 75 90 99 100; do    conbench dataset-selectivity-row-parquet --selectivity=$i ALL | awk 'NR>2' > skyhookdm-benchmarks/benchmarks-result/$(date '+%Y-%m-%d')/${{ github.sha }}/dataset-selectivity-${i}-row-parquet.json; done
          for i in 1 10 25 50 75 90 99 100; do    conbench dataset-selectivity-row-rados --selectivity=$i ALL | awk 'NR>2' > skyhookdm-benchmarks/benchmarks-result/$(date '+%Y-%m-%d')/${{ github.sha }}/dataset-selectivity-${i}-row-rados.json; done
          
      - name: Commit files
        run: |
          cd benchmarks/skyhookdm-benchmarks
          git config --local user.email "rahulagrawal799110@gmail.com"
          git config --local user.name "rahul799"
          git add benchmarks-result/$(date '+%Y-%m-%d')/*
          git commit -m "JSONS added" -a
          git push https://$USERNAME:$REPO_KEY@github.com/uccross/skyhookdm-benchmarks.git
        env:
          REPO_KEY: ${{secrets.PAT_FOR_PUSH}}
          USERNAME: rahul799
          

