name: Run Benchmarks

on:
  push:
    branches: [ skyhookdm-workflow ]
  pull_request:
    branches: [ skyhookdm-workflow ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: uccross/skyhookdm-arrow-benchmark:v0.2.0
    steps:
      - uses: actions/checkout@v2               
          
      - name: Install Python dependencies
        run: |
          python3.9 setup.py develop
          pip3.9 install -r requirements-test.txt
          pip3.9 install -r requirements-build.txt
          pip3.9 install coveralls
          
      - name: Setup Conbench
        run: |
          yum install postgresql-devel -y
          git clone https://github.com/ursacomputing/conbench.git
          cd conbench
          pip3.9 install -r requirements-test.txt
          pip3.9 install -r requirements-build.txt
          pip3.9 install -r requirements-cli.txt
          python3.9 setup.py develop
          
      - name: Run Tests
        run: |
          echo “alias python=/usr/local/bin/python3.9” >> ~/.bashrc
          source ~/.bashrc
          pytest -vv benchmarks/tests/test_dataset_filter_benchhmark.py

