name: Run Benchmarks

on:
  push:
    branches: [ skyhookdm-workflow, debug ]
  pull_request:
    branches: [ skyhookdm-workflow, debug ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: uccross/skyhookdm-arrow-benchmark:v0.2.0
      options: --privileged
    steps:
      - uses: actions/checkout@v2               
          
      - name: Install Python dependencies
        run: |
          python3.9 setup.py develop
          pip3.9 install -r requirements-test.txt
          pip3.9 install -r requirements-build.txt
          pip3.9 install coveralls
          
      - name: Setup Conbench
        run: |
          yum install postgresql-devel -y
          git clone https://github.com/ursacomputing/conbench.git
          cd conbench
          pip3.9 install -r requirements-test.txt
          pip3.9 install -r requirements-build.txt
          pip3.9 install -r requirements-cli.txt
          python3.9 setup.py develop
          
      - name: Setup Pyarrow with Skyhook
        run: |
          pip3.9 install --upgrade /pyarrow-*.whl
          
      - name: Run Tests
        run: |
          cp /usr/local/bin/python3.9 /usr/local/bin/python
          sh integration_ceph.sh
          pytest -vv benchmarks/tests/test_dataset_filter_benchhmark.py
          
      - name: Save results as JSON
        run: |
          cd benchmarks/
          mkdir artifacts
          conbench dataset-filter ALL > artifacts/dataset-filter-output.json
          
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: benchmarks/artifacts/dataset-filter-output.json

