name: Test Comment Workflow

on:
  push:
    branches: [ skyhookdm-workflow, debug ]
  pull_request:
    branches: [ skyhookdm-workflow, debug ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2               
          
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build output
            $(date '+%Y-%m-%d')
            ${{ github.sha }} 
            ![Result](/${{ github.sha }}/res.png)
            ![Test Image](https://github.com/ImageGlass/sample-images/blob/master/Samples/JPG/memory_leak/254c3574-7622-11e6-9585-2c8800776cfe.jpg)