name: Test Comment Workflow

on:
  push:
    branches: [ skyhookdm-workflow, debug ]
  pull_request:
    branches: [ skyhookdm-workflow, debug ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2              

      - name: Setup Pyarrow with Skyhook
        run: |
          echo "DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
          # echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          pip install python-decouple
          python3 test.py
        env:
          COMMIT_SHA=${{ GITHUB_TOKEN }}

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build output
            ${{ env.DATE }} 
            ![Result](https://github.com/uccross/skyhookdm-benchmarks/blob/main/benchmarks-result/${{ env.DATE }}/f092457dd67b9567dd693765c8a4ad9ea180fc61/dataset-selectivity-1-column-parquet.json)
            ![Test Image](https://github.com/ImageGlass/sample-images/blob/master/Samples/JPG/memory_leak/254c3574-7622-11e6-9585-2c8800776cfe.jpg)
          